name: camera_demo
description: A camera demo application with firebase incorperated

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  infinite_listview: ^1.0.1+1
  flutter_slidable: ^0.5.3
  draggable_scrollbar: ^0.0.4
  get_it: ^4.0.2
  built_collection: ^4.3.2
  flutter_bloc: ^3.2.0
  cloud_firestore: ^0.13.5
  equatable: ^1.1.1
  bloc: ^3.0.0
  built_value: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0


flutter:

  uses-material-design: true
